name = "LabJulia"
uuid = "ef6f2e11-3c27-461b-92b7-d0f3472eec4b"
authors = ["= <pjabardo@ipt.br> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
